### ISSUE TITLE
在vscodium上的使用问题

### ISSUE THREAD

**Issue by showgood163** [xicunyang/ts-space-prompt#1]
目前在vscodium上目前没法安装这个插件

两种可能的解决方式

一是github里release包，然后手动安装

二是上架vscodium的[marketplace](https://github.com/VSCodium/vscodium#extensions-and-the-marketplace)

请问作者是否有时间和精力解决这个问题？

**Comment by xicunyang** [comment]
> 目前在vscodium上目前没法安装这个插件
> 
> 两种可能的解决方式
> 
> 一是github里release包，然后手动安装
> 
> 二是上架vscodium的[marketplace](https://github.com/VSCodium/vscodium#extensions-and-the-marketplace)
> 
> 请问作者是否有时间和精力解决这个问题？

感谢使用~
之前没有接触过 vscodium ，所以没有做该工具的相关的插件发布工作，我今天会尝试发布一下~
我刚才创建了一个release包，地址：https://github.com/xicunyang/ts-space-prompt/releases/tag/v1.0.4
你可以先下载并本地安装一下试一试效果哈（不确定是否可以比较好的兼容）

再次感谢你的使用~

**Comment by xicunyang** [comment]
现在已经在 https://open-vsx.org/ 发布好了插件，可以通过这个地址访问：https://open-vsx.org/extension/xicunyang/ts-space-prompt 哈

**Comment by showgood163** [comment]
在vscodium上安装成功，感谢。
