### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by tjx666** [xicunyang/ts-space-prompt#2]
<img width="1512" alt="image" src="https://github.com/xicunyang/ts-space-prompt/assets/41773861/7119f9ad-928f-409b-9c99-ed11037aa70c">

```txt
Version: 1.88.1 (Universal)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:42:52.765Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0
```

**Comment by xicunyang** [comment]
没有get到你的意思哈，看起来你的截图是符合预期的，输入空格给出提示就是符合预期。

**Comment by xicunyang** [comment]
@tjx666

**Comment by tjx666** [comment]
我的问题，和 https://github.com/zardoy/typescript-vscode-plugins 有冲突。
